steps:
  
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - 'app-cluster'  
      - '--region'
      - 'us-central1'  
      - '--project'
      - '$PROJECT_ID'

  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-python-app:$COMMIT_SHA', '.']

  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/my-python-app:$COMMIT_SHA']

  
  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        kubectl set image deployment/my-python-app my-python-app=gcr.io/$PROJECT_ID/my-python-app:$COMMIT_SHA
        kubectl rollout status deployment/my-python-app


options:
  logging: CLOUD_LOGGING_ONLY
