steps:
  # Authenticate and configure kubectl to use the correct cluster
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - 'app-cluster'  # Name of your cluster
      - '--region'
      - 'us-central1'  # Your region
      - '--project'
      - '$PROJECT_ID'

  # Build Docker image and tag it with the commit SHA
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-python-app:$COMMIT_SHA', '.']

  # Push the Docker image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/my-python-app:$COMMIT_SHA']

  # Set the image in the Kubernetes deployment and verify the rollout
  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        kubectl set image deployment/my-python-app my-python-app=gcr.io/$PROJECT_ID/my-python-app:$COMMIT_SHA
        kubectl rollout status deployment/my-python-app

# Options
options:
  logging: CLOUD_LOGGING_ONLY
